account/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('register/', views.UserRegistrationView.as_view(), name = "register"),
    path('login/', views.UserLoginView.as_view(), name = "login"),
    path('logout/', views.UserLogoutView.as_view(), name = "logout"),
    path('profile/', views.UserBankAccountUpdateView.as_view(), name = "profile"),
]

mamar_bank/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import HomeView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name = "home"),
    path('account/', include("account.urls")),
    path('transactions/', include("transaction.urls")),
]

transaction/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('deposit/', views.DepositMoneyView.as_view(), name = 'deposit_money'),
    path('report/', views.TransactionReportView.as_view(), name = 'transaction_report'),
    path('withdraw/', views.WithdrawMoneyView.as_view(), name = 'withdraw_money'),
    path('loan_request/', views.LoanRequestView.as_view(), name = 'loan_request'),
    path('loans/', views.LoanListView.as_view(), name = 'loan_list'),
    path('loan/<int:loan_id>/', views.PayLoanView.as_view(), name = 'loan_pay'),
]

transaction/models.py
from django.db import models
from account.models import UserBankAccount
from .constants import TRANSACTION_TYPE
# Create your models here.
class Transaction(models.Model):
    account = models.ForeignKey(UserBankAccount, related_name = "transactions", on_delete=models.CASCADE) # ekjon user er multiple transactions hote pare
    amount = models.DecimalField(decimal_places = 2, max_digits = 12)
    balance_after_transaction = models.DecimalField(decimal_places = 2, max_digits = 12)
    transaction_type = models.IntegerField(choices = TRANSACTION_TYPE, null = True)
    timestamp = models.DateTimeField(auto_now_add = True) # jokhon ekta transaction object toiri hobe sei time ta store kore rakhbo.
    loan_approve = models.BooleanField(default = False)

    class Meta:
        # er kaj hocche, onek gula trasaction hote pare to amra segulake sort korbo timestamp er upor
        ordering = ['timestamp']

transaction/forms.py
from django import forms
from .models import Transaction

class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['amount', 'transaction_type']
    # Amra jokhon transaction niye kaj korte jabo thokhon user er account ta ekhane pass kore dibo. Ar ei TransactionForm ke inherite korbo (DepositForm, WithdrawForm, LoanRequestForm ei class gula TransactionForm ke inheite korbe)
    # Account ta je pop hocche ba ei jinish ta actually kothay use hocche seta amra dekhte parbo (views.py te get_form_kwargs er moddhe)
    def __init__(self, *args, **kwargs):
        self.account = kwargs.pop('account') # account value ke pop kore anlam. | keyword argument er moddhe built in kichu jinish ke pass kore dibo
        super().__init__(*args, **kwargs) # Parent class er __init__ ke overwrite korbo
        self.fields['transaction_type'].disabled = True # ei field disable thakbe
        self.fields['transaction_type'].widget = forms.HiddenInput() # user er theke hide kora thakbe

    def save(self, commit = True):
        self.instance.account = self.account # je user ta request korteche tar kono object jodi amader database e thake tahole sei instance er account je jabo, giye self.account ke rekhe dibo
        # jekono trasaction er por balance take update kore dibo.
        self.instance.balance_after_transaction = self.account.balance # suppouse 0(main balance)--> 5000(deposit) = 5000(total_balance/balance_after_transaction)
        return super().save() # parent class (ModelForm) er save function ke call kore dilam
    

class DepositForm(TransactionForm):
    def clean_amount(self): # amount field ke filter korbo | clean_amount --> builtin ekta function (clean_... jei field ta niye kaj korte chai sei field ta use korbo, jehetu amount niye kaj kortechi tai amount niyechi)
        min_deposit_amount = 100
        amount = self.cleaned_data.get('amount') # user er fillup kora form theke amount field er value ke niye ashlam
        if amount < min_deposit_amount:
            raise forms.ValidationError( # raise hocche error ke show koranor jonno ekta keyword
                f'You need to deposit at least ${min_deposit_amount}'
            )
        return amount
    
class WithdrawForm(TransactionForm):
    def clean_amount(self):
        account = self.account # je user request korteche tar account
        min_withdraw_amount = 500
        max_withdraw_amount = 20000
        balance = account.balance
        amount = self.cleaned_data.get('amount')
        if amount < min_withdraw_amount:
            raise forms.ValidationError(
                f'You can withdraw at least ${min_withdraw_amount}'
            )
        if amount > max_withdraw_amount:
            raise forms.ValidationError(
                f'You can withdraw at most ${max_withdraw_amount}'
            )
        if amount > balance:
            raise forms.ValidationError(
                f'You have ${balance} in your account.'
                'You can not withdraw more than your account balance'
            )
        return amount
    

class LoanRequestForm(TransactionForm):
    def clean_amount(self):
        amount = self.cleaned_data.get('amount')
        return amount

# Loan koybar neya hoyche seta views er moddhe korechi. Koybar loan neya hoyeche eta model er sathe connected ba model theke pabo. Tai ei kaj ta form er moddhe na kore views er moddhe korechi karon form er kaj form e ar model er kaj views e koratai better.
# form er kaj form e rakhte hoy
# model er kaj views e rakhte hoy.

transaction/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views.generic import CreateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Transaction

from . forms import DepositForm, WithdrawForm, LoanRequestForm
from .constants import DEPOSIT, WITHDRAWAL, LOAN, LOAN_PAID
from django.contrib import messages
from datetime import datetime
from django.db.models import Sum
from django.views import View
from django.urls import reverse_lazy

from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import render_to_string
# Create your views here.

#-------------------------------------------------------------------------
def send_transaction_email(user, amount, subject, template):
    message = render_to_string(template, {
        'user' : user,
        'amount' : amount,
    })
    send_email = EmailMultiAlternatives(subject, '', to=[user.email])
    send_email.attach_alternative(message, "text/html")
    send_email.send()
#-------------------------------------------------------------------------
# ei view ke inherit kore amra deposit, withdraw, loan request er kaj korbo
class TransactionCreateMixin(LoginRequiredMixin, CreateView):
    template_name = 'transaction/transaction_form.html'
    model = Transaction
    title = '' # ei title view ta class based view te thake na. (HTML title ja frontend e show korbe) Eita kono ekta koushol use kore pass kore dibo.
    success_url = reverse_lazy('transaction_report')

    """
    "TransactionForm & TransactionCreateMixin er combination e nicher documentation/lekha ta"
        jokhoni Transactionform er ekta object toiri hobe, ba ekta form e kono ekta user kono ekta jinish pass korbe
        tokhon jeta hobe --> tokhoni amader views er get_form_kwargs er account value ta amader TransactionForm er moddhe chole ashbe
        ashar pore ekhane pop hobe (check views.py). Pop hobar por pori user dekhbe je transaction_type ei field ta disable kora
        sei jinish ta fillup korte parbena, amra fillup kore dibo backend theke. Then jokhon eta save korte jabe orthat submit button click korbe
        tokhon tar account ta capture korar pore tar tar balance take ber kore niye ashlam ebong balance_after_transaction ta amra tar balance ta diye update kore dicchi prottekta bar.
        then reture kore dichhi return super().save ke --> Parent je chilo(Built-in) take overwrite kore eke save kore dicchi. 
    """
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            # je request korteche tar account
            'account' : self.request.user.account, # ei account ta form er moddhe ("def __init__(self, *args, **kwargs):") access kortechilam account naame (same naam duijaygatei thakte hobe)
        })
        return kwargs
    
    # Transaction vede Title nirdharon korar jonno
    # context ta frontend e send kore dibo (Diposite, Withdraw, LoanRequest)
    # jokhon amra TransactionCreateMixin ke iherite kore Deposit/Withdraw/LoanRequest Form toiri korbo, tokhon user chaile just title ta filup korlei ei function ta call hobe & title ta save hoye jabe.
    def get_context_data(self, **kwargs):
        # built-in context ke niye ashbo tarpor setake context.update er sahajje overwrite kore dibo.
        context = super().get_context_data(**kwargs)
        context.update({
            'title' : self.title
        })
        return context

class DepositMoneyView(TransactionCreateMixin):
    # jehetu template, model egula Deposit, Withdraw, LoanRequest sobar jonno same thakbe
    # tai egula ekhane ar lagbena.
    # form jehtu alada alada tai form lagbe.
    form_class = DepositForm
    title = 'Deposit'

    # return the initial data to use for forms on this view.
    # initial kono data ami form er moddhe agei pass kore dite chai. Jemon ekjon User form ta submit kore nai, just view korteche thik oi muhurte ami ekta data ke push kore dilam. User dekhte pacche na. 
    def get_initial(self):
        initial = {'transaction_type' : DEPOSIT}
        return initial
    
    # user form ta fillup korar por backend theke check korbo form ta valid kina, orthat form requirments onujayi fillup hoyeche kina. 
    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        account = self.request.user.account
        account.balance += amount
        account.save(
            update_fields = ['balance']  
        )
        messages.success(self.request, f'${amount} was deposited to your account successfully')
        #----------------------------------
        # Sending Email
        send_transaction_email(self.request.user, amount, "Deposit Message", 'transaction/deposit_mail.html')
        #----------------------------------
        return super().form_valid(form)
    
class WithdrawMoneyView(TransactionCreateMixin):
    form_class = WithdrawForm
    title = 'Withdraw Money'

    def get_initial(self):
        initial = {'transaction_type' : WITHDRAWAL}
        return initial
    
    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        account = self.request.user.account
        account.balance -= amount
        account.save(
            update_fields = ['balance']
        )
        messages.success(self.request, f"Successfully withdrawn ${amount} from your account")
        #----------------------------------------
        # Sending Email
        send_transaction_email(self.request.user, amount, "Withdrawal Message", 'transaction/withdraw_mail.html')
        #----------------------------------------
        return super().form_valid(form)

class LoanRequestView(TransactionCreateMixin):
    form_class = LoanRequestForm
    title = 'Request For Loan'

    def get_initial(self):
        initial = {'transaction_type' : LOAN}
        return initial
    
    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        # Transaction Model er object theke kichu jinish filter kore niye ashlam. 
        # Accont filter korbe, transaction_type (3 means LOAN) tarpor check kore dekbe je Loan_Approve True kina, jodi True Hoy tahole count kore niye ashbe. (Total kotobar Loan niyeche seta count kora holo)
        current_loan_count = Transaction.objects.filter(account = self.request.user.account, transaction_type = 3, loan_approve = True).count() # 3 means LOAN jeta constants er moddhe bole deya ache. 3 er bodole LOAN dileu hoto
        if current_loan_count >= 3:
            return HttpResponse("You have crossed your limits")
        messages.success(self.request, f"Loan request for amount ${amount} has been successfully sent to admin")
        #----------------------------------
        # Sending Email
        send_transaction_email(self.request.user, amount, "Loan Request Message", 'transaction/loan_request_mail.html')
        #----------------------------------
        return super().form_valid(form)
    
class TransactionReportView(LoginRequiredMixin, ListView):
    template_name = 'transaction/transaction_report.html'
    model = Transaction
    balance = 0 # eta built-in kono field na.
    context_object_name = 'report_list'

    def get_queryset(self):
        # jodi user kono type filter na kore tahole tar total transaction report dekhabo.
        queryset = super().get_queryset().filter(
            account = self.request.user.account
        )
        start_date_str = self.request.GET.get('start_date')
        end_date_str = self.request.GET.get('end_date')

        if start_date_str and end_date_str:
            start_date = datetime.strptime(start_date_str, '%Y-%m-%d').date()
            end_date = datetime.strptime(end_date_str, '%Y-%m-%d').date()
        
            # User jodi filter kore tahole queryset ta emon hobe.
            # Eta bujhte somossha hole ba kothin lagle (Nicher ta kheyal kori)
            # user er account er information gulake filter kortechi. (queryset = super().get_queryset().filter(account = self.request.user.account)) ei account er user er
            queryset = queryset.filter(timestamp__date__gte = start_date, timestamp__date__lte = end_date) # gte --> greater than equal, lte --> less than equal

            self.balance = Transaction.objects.filter(timestamp__date__gte = start_date, timestamp__date__lte = end_date).aggregate(Sum('amount'))['amount__sum']
        else:
            self.balance = self.request.user.account.balance
        return queryset

    def get_context_data(self, **kwargs):
        # built-in context ke niye ashbo tarpor setake context.update er sahajje overwrite kore dibo.
        context = super().get_context_data(**kwargs)
        context.update({
            'account' : self.request.user.account
        })
        return context
    
class PayLoanView(LoginRequiredMixin, View):
    def get(self, request, loan_id):
        loan = get_object_or_404(Transaction, id = loan_id)
        
        if loan.loan_approve: # ekjon user loan pay korte parbe tokhoni jokhon tar loan approve hobe.
            user_account = loan.account
            if loan.amount < user_account.balance:
                user_account.balance -= loan.amount
                loan.balance_after_transaction = user_account.balance
                user_account.save()
                loan.transaction_type = LOAN_PAID
                loan.save()
                return redirect('loan_list')
            else:
                messages.error(self.request, f'Loan amount is greater than available balance')
                return redirect('loan_pay')

class LoanListView(LoginRequiredMixin, ListView):
    model = Transaction
    template_name = 'transaction/loan_request.html'
    context_object_name = 'loans' # total loan list ta ei loans er moddhe thakbe.

    def get_queryset(self):
        user_account = self.request.user.account
        queryset = Transaction.objects.filter(account = user_account, transaction_type = LOAN)

transaction/templates/transaction/approval_mail.html
<p>Hello {{user.first_name}} {{user.last_name}}</p>
<h2>Congratulations!! Your Loan Request for ${{amount}} has been Approved.</h2>
<p>After Loan Approval your total amount is {{user.account.balance}}</p>
<p>Thanks for banking with us</p>
<p>Mamar Bank</p>

transaction/templates/transaction/deposit_mail.html
<p>Hello {{user.first_name}} {{user.last_name}}</p>
<p>Your Deposit request for ${{amount}} has been successfully completed. After Deposit your total amount is {{user.account.balance}}</p>
<p>Thanks for banking with us</p>
<p>Mamar Bank</p>

transaction/templates/transaction/loan_request.html
{% extends 'base.html' %} 
{% block head_title %}{{ title }}{% endblock %} 
{% block content %}
<div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md">
  <h1 class="font-bold text-3xl text-center pb-5 pt-2">Loan Report</h1>
  <hr />
  <table
    class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border dark:border-neutral-500"
  >
    <thead class="bg-purple-900 text-white text-left">
      <tr
        class="bg-gradient-to-tr from-indigo-600 to-purple-600 rounded-md py-2 px-4 text-white font-bold"
      >
        <th class="px-4 py-2">LOAN ID</th>
        <th class="px-4 py-2">Loan Amount</th>
        <th class="px-4 py-2">Loan Approved</th>
        <th class="px-4 py-2">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for loan in loans %}
      <tr class="border-b dark:border-neutral-500">
        <td class="px-4 py-2">
         {{ loan.id }}
        </td>
        <td class="px-4 py-3 text-s border">
          <span
            class="px-2 py-1 font-bold leading-tight rounded-sm text-green-700 bg-green-100"
          >
            {{ loan.amount }}
          </span>
        </td>
        <td class="px-4 py-2">
          {{ loan.loan_approve }}
        </td>
        <td class="px-4 py-2">
          {% if loan.loan_approve %}
          <a class="font-bold bg-red-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg" href='{% url "loan_pay" loan.id %}'>Pay</a>
          {% else %}
          <p class="font-bold text-red-700 bg-red-100">Loan Pending</p>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

transaction/templates/transaction/loan_request_mail.html
<h3>Hello {{user.first_name}} {{user.last_name}}</h3>
<h3>Your Loan request for ${{amount}} has been successfully sent to Admin. Please wait for confirmation email</h3>
<h3>Thanks for banking with us</h3>
<h3>Mamar Bank</h3>

transaction/templates/transaction/transaction_form.html
{% extends 'base.html' %} 
{% block head_title %}{{ title }}{% endblock %} {% block content %}

<div class="w-full flex mt-5 justify-center ">
    <div class="bg-white w-5/12 rounded-lg">
        {% if title == 'Request For Loan' %}
            <div><a class="font-bold text-blue text-center pb-5 pt-10 px-5" href="{% url 'loan_list' %}">View All Loan List</a></div>
        {% endif %}
        
        <h1 class="font-bold text-3xl text-center pb-5 pt-10 px-5">{{ title }}</h1>
        <form method="post" class="px-8 pt-6 pb-8 mb-4">
            {% csrf_token %}

            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                    Amount
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="amount" id="amount" type="number" required placeholder="Amount">
            </div>
            {% if form.amount.errors %} 
                {% for error in form.amount.errors %}
                    <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                {% endfor %} 
            {% endif %}
            <div class="flex w-full justify-center">
                <button class="bg-blue-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg" type="submit">
                    Submit
                </button>
            </div>
        </form>
    </div>
    
</div>
{% endblock %} 

transaction/templates/transaction/transaction_report.html
{% extends 'base.html' %} 
{% load static %}
{% comment %} mone kori ami $10000 deposit korechi, amake dekhabe 10,000.00 eije 10 er por ekta . tarpor 3 ta 0 tarpor . tarpor 2 ta 0 ei kaj tai humanize jinish ta kore thake {% endcomment %}
{% load humanize %} 
{% block head_title %} Transaction Report{% endblock %} {% block content %}


<div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md">
  <h1 class="font-bold text-3xl text-center pb-5 pt-2">Transaction Report</h1>
  <hr />
  <form method="get" action="{% url 'transaction_report' %}">
    <div class="flex justify-center">
      <div
        class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12 mx-2"
      >
        <label for="start_date">From:</label>
        <input
          class="appearance-none w-full outline-none focus:outline-none active:outline-none"
          type="date"
          id="start_date"
          name="start_date"
        />
      </div>
 
      <div
        class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12"
      >
        <label for="end_date">To:</label>
        <input
          class="appearance-none w-full outline-none focus:outline-none active:outline-none"
          type="date"
          id="end_date"
          name="end_date"
        />
      </div>
      <div class="mt-10 pl-3 pr-2 flex justify-between items-center relative w-4/12">
        <button
          class="bg-blue-900 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
          type="submit"
        >
          Filter
        </button>
      </div>
    </div>
  </form>
  <table
    class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border dark:border-neutral-500"
  >
    <thead class="bg-purple-900 text-white text-left">
      <tr
        class="bg-gradient-to-tr from-indigo-600 to-purple-600 rounded-md py-2 px-4 text-white font-bold"
      >
        <th class="px-4 py-2">Date</th>
        <th class="px-4 py-2">Transaction Type</th>
        <th class="px-4 py-2">Amount</th>
        <th class="px-4 py-2">Balance After Transaction</th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in report_list %}
      <tr class="border-b dark:border-neutral-500">
        <td class="px-4 py-2">
          {{ transaction.timestamp|date:"F d, Y h:i A" }}
        </td>
        <td class="px-4 py-3 text-s border">
          <span
            class="px-2 py-1 font-bold leading-tight rounded-sm {% if transaction.get_transaction_type_display == 'Withdrawal' %} text-red-700 bg-red-100 {% else %} text-green-700 bg-green-100 {% endif %}"
          >
            {{ transaction.get_transaction_type_display }}
          </span>
        </td>
        <td class="px-4 py-2">
          $ {{ transaction.amount|floatformat:2|intcomma }}
        </td>
        <td class="px-4 py-2">
          $ {{ transaction.balance_after_transaction|floatformat:2|intcomma }}
        </td>
      </tr>
      {% endfor %}
      <tr class="bg-gray-800 text-white">
        <th class="px-4 py-2 text-right" colspan="3">Current Balance</th>
        <th class="px-4 py-2 text-left">
          $ {{ account.balance|floatformat:2|intcomma }}
        </th>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}

transaction/templates/transaction/withdraw_mail.html
<h3>Hello {{user.first_name}} {{user.last_name}}</h3>
<h3>Your Withdrawal request for ${{amount}} has been successfully completed. After Withdrawal your total amount is {{user.account.balance}}</h3>
<h3>Thanks for banking with us</h3>
<h3>Mamar Bank</h3>